CREATE TABLE CART_SAVE(
    id INT AUTO_INCREMENT PRIMARY KEY,
    userid INT NOT NULL,
    course SMALLINT NOT NULL,
    FOREIGN KEY (userid) REFERENCES USERS(userid),

    FOREIGN KEY (course) REFERENCES COURSE_DATA(id)
);