CREATE TABLE COURSES_REL(
    courseid SMALLINT NOT NULL,
    offerid SMALLINT NOT NULL,
    PRIMARY KEY (courseid, offerid),
    FOREIGN KEY (courseid) REFERENCES COURSE_DATA(id),
    FOREIGN KEY (offerid) REFERENCES COURSE_OFFER(id)
);
