CREATE TABLE REGISTERED_COURSES(
    registeredID INT AUTO_INCREMENT PRIMARY KEY,
    userName varchar(50) NOT NULL,
    keycode INT NOT NULL,
    enrollmentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (userName) REFERENCES USERS(userName)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (keycode) REFERENCES COURSE_DATA(keycode)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);