CREATE TABLE REGISTERED_COURSES(
    registeredID INT AUTO_INCREMENT PRIMARY KEY,
    username varchar(50) NOT NULL,
    keycode INT NOT NULL,
    enrollmentDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (username) REFERENCES USERS(username)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    FOREIGN KEY (keycode) REFERENCES COURSE_DATA(keycode)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);