CREATE TABLE STUDENT_STUDY_FIELD(
  studyfieldid INT AUTO_INCREMENT PRIMARY KEY, 
  studentid INT NOT NULL,
  programid SMALLINT NOT NULL,
  degreeaward BOOLEAN DEFAULT FALSE,

  FOREIGN KEY (studentid) REFERENCES STUDENTS(studentid)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  
  FOREIGN KEY (programid) REFERENCES ACADEMIC_PROGRAMS(programid)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);